#!/bin/bash

p=`realpath $0`
scripts=`dirname $p`
internaldisplay=eDP-1
externaldisplay=`$scripts/x-connected-displays.sh`

xrandr --output $internaldisplay --auto
xrandr --output $externaldisplay --left-of $internaldisplay --auto
